INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES (' landslides', 'A landslide is described as an outward and downward slope movement of an abundance of slope-forming materials including rock, soil, artificial, or even a combination of these things.', NULL, '15') ;

INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Blizzard', 'A blizzard is a severe snowstorm characterized by strong sustained winds of at least 35 mph and lasting for a prolonged period of time—typically three hours or more. A ground blizzard is a weather condition where snow is not falling but loose snow on the ground is lifted and blown by strong winds', 'Try to stay warm because blizzards may lead to high degree of temperature which may lead to death.', '125');

INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Droughts', 'Drought is the unusual dryness of soil caused by levels of rainfall significantly below average over a prolonged period. Hot dry winds, shortage of water, high temperatures and consequent evaporation of moisture from the ground can also contribute to conditions of drought. Droughts result in crop failure and shortages of water.', NULL, '67') ;

INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Earthquake', NULL, 'Stay Away from any parts not stable and may fall to stay safe from the falling parts ', '151'); 

INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Fire', 'electric mass may lead to huge fire in your building and may extend no many of the near buildings ', 'Always try to have Fire protection system in your building', '15');

INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Flight Drop', 'Motors stopped working in the sky', 'Check motors before the flight begin', '51') ;
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Floods', 'A flood is an overflow of water that covers the earth. This overflow can damage buildings and cars in its path', 'governments must build dams to prevent this water from going everywhere in the town ', '235') ;
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Gas Leaks', 'Problems in the pumps which may lead that all the gas are not transported correctly .', 'Every month there must be checks on the all pumps', '51');
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Heat wave', 'A heat wave is a period of excessively hot weather, which may be accompanied by high humidity, especially in oceanic climate countries. While definitions vary, a heat wave is usually measured relative to the usual weather in the area and relative to normal temperatures for the season.', NULL, '511') ;
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('massacre', 'insane king or citizen starts to kill a huge amount of peoples ', NULL, '97') ;
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Nuclear Meltdown', 'Nuclear Weapon used in fighting between countries ', 'the world should refuse all the nuclear weapons ', '11');
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Oil Spills', 'Oil spills may happen by accident while the car is transporting the oil from place to another ', NULL, '15') ;
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Road accident', 'Driving Drunk , or driving with high speed which is not allowed on some roads', 'Stay alert while driving and drive below the maximum speed allowed of the road', '510') ;
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Ship Drowned', 'Ship remove water cycle stopped working suddenly', 'check all equipments on the ship daily ', '63') ;
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Storm', 'A storm is any disturbed state of an environment or in an astronomical bodys atmosphere especially affecting its surface, and strongly implying severe weather', NULL, '15');
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Terrorism', 'the use or threatened use of violence for the purpose of creating fear in order to achieve a political, religious, or ideological goal. Targets of terrorist acts can be anyone, including private citizens, government officials, military personnel, law enforcement officers, firefighters, or people serving in the interests of governments.\r\n\r\n', 'Police and Army must prevent any type of Terrorism ', '156');
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Tornado', 'A tornado is a rapidly rotating column of air that is in contact with both the surface of the Earth and a cumulonimbus cloud or, in rare cases, the base of a cumulus cloud', 'Stay away from the tornado center so the tornado wont be able to effect you ', '125') ;
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Tsunamis', 'A tsunami consists of huge waves caused by either an underwater earthquake or volcanic eruption', 'Stay Away from any beaches , go to the most far place from the water', '30') ;
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('Volcano', 'COre Melting', 'Surrounding Evacuation', '10') ;
INSERT INTO `disaster` (`name`, `possible_causes`, `precautions`, `no_of_prev_occur`) VALUES ('War', 'War is a conflict between relatively large groups of people, which involves physical force inflicted by the use of weapons. Warfare has destroyed entire cultures, countries, economies and inflicted great suffering on humanity. Other terms for war can include armed conflict, hostilities, and police action. Acts of war are normally excluded from insurance contracts and sometimes from disaster planning.', 'Countries must use democracy in conflicts not power and weapons ', '163') ;
