

INSERT INTO `incident` (`id`, `eco_loss`, `year`, `month`, `day`, `description`, `location`, `name`, `type`) VALUES
(1, 1000000, 2018, 4, 12, 'Huge Eruption', 'Egypt', 'Volcano', NULL),
(3, 1500000, 1970, 10, 6, 'Israil took sinai from egypt so egypt had to make a war to restore it back', 'Egypt , sinai', '6 October War', 'War'),
(4, 90000000, 1945, 9, 1, 'World War II  also known as the Second World War, was a global war that lasted from 1939 to 1945 The vast majority of the worlds countries including all the great powers eventually formed two opposing military alliances  the Allies and the Axis', 'France', 'World War 2', 'War'),
(5, 97697660, 1914, 5, 28, 'World War I, also known as the First World War or the Great War, was a global war originating in Europe', 'UK', 'World War I', 'War'),
(6, 80000000, 2003, 3, 20, 'The Iraq War was a protracted armed conflict that began in 2003 with the invasion of Iraq by a United States-led coalition that overthrew the government of Saddam Hussein. The conflict continued for much of the next decade as an insurgency emerged to oppose the occupying forces and the post-invasion Iraqi government.', 'iraq', 'Iraq War', 'War'),
(7, 5122333, 1988, 8, 2, 'The Gulf War, codenamed Operation Desert Shield for operations leading to the buildup of troops and defense of Saudi Arabia and Operation Desert Storm in its combat phase, was a war waged by coalition', 'Saudi Arabia', 'Gulf War', 'War'),
(8, 99999999, 1994, 12, 6, 'America Throw nuclear bomb on hiroshema', 'Japan', 'Hiroshema bomb', 'Nuclear Meltdown'),
(9, NULL, 2002, 12, 23, 'Hittler wanted to kill all the joush people', 'german', 'Hitler massacre', 'massacre'),
(10, NULL, 2002, 12, 23, 'Hittler wanted to kill all the joush people', 'german', 'Hitler massacre', 'massacre'),
(11, NULL, 1994, 12, 12, 'Mohamed ali wanted to kill all the mmalek', 'egypt', 'Galout eyes', 'massacre'),
(12, 9500, 2010, 12, 5, 'a huge number of cars crashed', 'usa', 'high road accident', 'Road accident'),
(13, 5000000, 2009, 12, 20, 'oil spilled in the desert because the transportation car fall', 'egypt', 'The huge loss', 'Oil Spills'),
(14, 980000, 2005, 5, 15, 'huge ship called titanic drowned in the ocean', 'usa', 'titanic drowned', 'Ship Drowned'),
(15, 9500, 2005, 12, 22, 'the flight motor suddenly stopped and alot of people died', 'Saudi Arabia', 'the flight gone', 'Flight Drop'),
(16, 500000, 2001, 12, 31, NULL, 'egypt , el mansoura', 'Mansoura Gas', 'Gas Leaks'),
(17, 870000, 2000, 12, 5, 'A fire started in building then started to move forward throw all cairo buildings', 'Egypt , cairo', 'Cairo big fire', 'Fire'),
(18, NULL, 2009, 12, 5, 'someone killed the master of the group', 'usa', 'Assisinatetion', 'Terrorism'),
(19, NULL, 2009, 12, 5, 'someone killed the master of the group', 'usa', 'Assisinatetion', 'Terrorism'),
(20, 9500000, 1995, 12, 5, 'the dogs group blowed up gas factory', 'qatar', 'The dogs', 'Terrorism'),
(21, NULL, 2018, 12, 23, 'arab countries wanted to take revenge from israel', 'israel', 'Vectory Again', 'War'),
(22, 10000, 2009, 12, 12, 'a huge fire suddenly made up all the trees  goes down', 'usa', 'Forest Fire', 'Fire'),
(31, 90000, 2017, 5, 5, 'Blizzard below up in the middle of europe', 'europe , france', 'killing Blizzard', 'Blizzard'),
(32, 67500, 1988, 12, 24, 'there was no water in the country so all the planets died', 'egypt', 'Drought farms', 'Droughts'),
(33, 150000, 2011, 5, 25, 'The 2011 earthquake off the Pacific coast of TÅhoku was a magnitude 9.0â€“9.1 undersea megathrust earthquake off the coast of Japan', 'japan', 'TÅhoku earthquake', 'Earthquake'),
(34, 900000, 1964, 12, 4, 'The 1964 Alaskan earthquake, also known as the Great Alaskan earthquake and Good Friday earthquake', 'alaska', 'Alaska earthquake', 'Earthquake'),
(35, 214444, 1906, 12, 4, 'The 1906 San Francisco earthquake struck the coast of Northern California', 'san francisco', 'San  earthquake', 'Earthquake'),
(36, 1421424, 2017, 2, 14, 'The 2017 Puebla earthquake struck at 13:14 CDT on 19 September 2017 with an estimated magnitude of Mw 7.1 and strong shaking for about 20 seconds. Its epicenter was about 55 km south of the city of Puebla.', 'puebla', 'Puebla earthquake', 'Earthquake'),
(37, NULL, 2009, 12, 12, 'Arenal Volcano is an active andesitic stratovolcano in north-western Costa Rica around 90 km northwest of San JosÃ©, in the province of Alajuela, canton of San Carlos, and district of La Fortuna. The Arenal volcano measures at least 1,633 metres high. It is conically shaped with a crater 140 metres in diameter.', 'Arenal', 'Arenal Volcano', 'Volcano'),
(38, 1900, 1944, 12, 12, 'Mount Vesuvius is a somma-stratovolcano located on the Gulf of Naples in Campania, Italy, about 9 km east of Naples and a short distance from the shore. It is one of several volcanoes which form the Campanian volcanic arc.', 'Venus', 'Mount Vesuvius', 'Volcano'),
(39, NULL, 2018, 1, 1, 'Mount Etna, or Etna, is an active stratovolcano on the east coast of Sicily, Italy, in the Metropolitan City of Catania, between the cities of Messina and Catania. It lies above the convergent plate margin between the African Plate and the Eurasian Plat', 'Etna', 'Mount Etna', 'Volcano'),
(40, 95000, 1984, 1, 1, 'Mauna Loa is one of five volcanoes that form the Island of Hawaii in the U.S. state of HawaiÊ»i in the Pacific Ocean. The largest subaerial volcano in both mass and volume, Mauna Loa has historically been considered the largest volcano on Earth, dwarfed only by Tamu Massif', 'usa', 'Mauna Loa', 'Volcano'),
(41, 5000, 1999, 5, 12, 'Mayon, also known as Mayon Volcano or Mount Mayon, is an active stratovolcano in the province of Albay in Bicol Region, on the large island of Luzon in the Philippines', 'Philippines', 'Mayon Volcano', 'Volcano'),
(42, 90000, 1990, 1, 1, NULL, 'Texas', 'Galveston', 'Storm'),
(43, 22122, 1928, 1, 1, NULL, 'fla', 'Lake Okeechobee', 'Storm'),
(44, 90000, 2005, 1, 1, 'Katrina is a huge storm that happens in usa every year  , it comes with a massive distruction', 'usa', 'Katrina', 'Storm'),
(45, 90000, 1997, 12, 12, 'The Thredbo landslide was a catastrophic landslide that occurred at the village and ski resort of Thredbo, New South Wales, Australia, on 30 July 1997. Two ski lodges were destroyed and a total of 18 died', 'therdpo', 'Thredbo landslide', 'landslides'),
(46, 900200, 1949, 1, 10, 'The Khait or Hoit landslide occurred on July 10, 1949 in the Hoit district in the Gharm Oblast in the Tajikistan, then part of the Soviet Union. Khait is a transliteration from Russian: Ð¥Ð°Ð¸Ñ‚; local modern spelling: Hoit.', 'Tajikistan', 'Khait landslide', 'landslides'),
(47, 95000, 2014, 3, 1, 'On 30 July 2014, a landslide occurred in the village of Malin in the Ambegaon taluka of the Pune district in Maharashtra, India. The landslide, which hit early in the morning while residents were asleep, was believed to have been caused by a burst of heavy rainfall, and killed at least 151 people', 'India', 'Malin landslide', 'landslides'),
(48, 9000, 1909, 9, 29, 'The Frank Slide was a rockslide that buried part of the mining town of Frank, Northwest Territories, Canada at 4:10 am on April 29, 1903. Over 82 million tonnes of limestone rock slid down Turtle Mountain within 100 seconds, obliterating the eastern edge of Frank, the Canadian Pacific Railway line and the coal mine.', 'Canada', 'Frank Slide', 'landslides'),
(49, 9000, 2011, 9, 21, NULL, 'East Africa', 'East Africa', 'Droughts'),
(50, 900000, 2013, 5, 20, 'On the afternoon of Monday, May 20, 2013, a large and very powerful EF5 tornado ravaged Moore, Oklahoma, and adjacent areas, with peak winds estimated at 210 mph, killing 24 people and injuring 212 others.', 'Oklahoma', 'Moore Tornado', 'Tornado');

INSERT INTO `natural_disaster` (`id`, `freq`, `physical_parameters`) VALUES
(31, 2, 'Tempreature:100 , range 500 meter'),
(32, 1, 'Range:90000 meter square , took 1  year to fix it'),
(33, 1, 'magnitude:9 , range 200 meter'),
(34, NULL, 'magnitude:9.1 , range 300 meter'),
(35, 2, 'magnitude:8.1 , range 200 meter'),
(36, 1, 'magnitude:7.4, range 55 kilo meter'),
(37, 1, 'Last eruption: 2010 Elevation: 1,670 m Prominence: 813 m'),
(38, 1, 'Last eruption: March 1944 Elevation: 1,281 m Prominence: 1,232 m'),
(39, 1, 'Elevation: 3,350 m Area: 1,190 kmÂ²'),
(40, 1, 'Elevation: 4,169 m Area: 5,271 kmÂ²'),
(41, 1, 'Elevation: 2,463 m Prominence: 2,447 m'),
(42, 2, '8000 death'),
(43, 1, '2500 death'),
(44, 1, '1800 death'),
(45, 1, 'Cause: Heavy rain, melting snow and a leaking water main Total number of deaths: 18'),
(46, 1, NULL),
(47, 1, 'Property damage: 40 houses Missing: 100 Total number of deaths: 151'),
(48, 1, 'Death(s): 70-90+'),
(49, 1, 'threatened the livelihood of 9.5 million people'),
(50, 1, 'Damage: 2 billion USD (estimate) Start date: May 20, 2013 Areas affected: McClain and Cleveland counties in Oklahoma; particularly the city of Moore Highest winds: 210 mph (340 km/h) Max rating1: EF5 tornado');
INSERT INTO `human_made` (`id`, `causes`) VALUES
(3, 'Israil refused to give sinai back to egypt'),
(4, 'Conflict between countries after world war 1'),
(5, 'conflicts between counties which one have more power'),
(6, 'America wanted to steal iraq oil'),
(7, 'conflict between usa and saudi arabia'),
(8, 'America wanted to make revenge'),
(9, NULL),
(10, NULL),
(11, NULL),
(12, 'oil dropped on the high road'),
(13, 'fallen transportation car'),
(14, NULL),
(15, 'motors stopped working'),
(16, 'gas pump suddenly blow up'),
(17, 'Electric mass'),
(18, 'the master refused to give him money'),
(19, 'the master refused to give him money'),
(20, 'to make the country pay more and more'),
(21, 'israel must pay'),
(22, 'some one unknown made it');
